# Generated by Django 4.2.5 on 2023-10-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Doors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='EngineSize',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Odometer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Year',
            field=models.IntegerField(),
        ),
    ]
