# Generated by Django 4.2.5 on 2023-10-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCApp', '0002_alter_listing_doors_alter_listing_enginesize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='BodyStyle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='CarModel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Doors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='DriveType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='EngineSize',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ExteriorColor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='FuelType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Make',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='New',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Odometer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Registration',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Transmission',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='WOF',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Year',
            field=models.IntegerField(null=True),
        ),
    ]
