# Generated by Django 4.2.5 on 2023-10-10 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KCApp', '0003_alter_listing_bodystyle_alter_listing_carmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='CreatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
