# Generated by Django 4.2.5 on 2023-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCApp', '0004_listing_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='CreatedBy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
